name: Health Check
on:
  pull_request: {}
jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: healthcheck
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENDPOINTS: |
            /xref/meta/version/
            /xref/
        shell: bash
        run: |
          base_url="https://respec.org"
          IFS=$'\n' read -r -d '' -a urls <<< "$ENDPOINTS"
          for url in "${urls[@]}"; do
            printf "${base_url}${url} ... ";
            full_url="${base_url}${url}?healthcheck=true"
            http_code=$(curl -s -o /dev/null -L -w "%{http_code}" "$full_url")
            echo "$http_code"
            if [ $http_code != 200 ]; then
              echo "Reporting failure on Slack..."
              curl --fail -H "Content-Type: application/json" \
                -d "{ \"text\": \"🔴 HEAD $http_code ${url}\" }" \
                "$SLACK_WEBHOOK_URL"
            fi
          done;
