name: Health Check
on:
  pull_request: {}
jobs:
  healthcheck:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ENDPOINTS: |-
        /xref/meta/version/
        /xref/
    steps:
      - name: healthcheck
        shell: bash
        run: |
          bash <(curl -s https://raw.githubusercontent.com/marcoscaceres/respec.org/healthcheck-easier/.github/workflows/healthcheck.sh)
